### ISSUE TITLE
submission Form Validation

### ISSUE THREAD

**Issue by teesloane** [speakfriend/speakfriend#29]
All fields on the form should be required. this involves:

- displaying an asterisk (`*`) next to the form field name
- preventing submission until the fields are filled out correctly.

For now, this should be simple we can:

- write the validation in the home/index.js route (no need for a library or abstraction yet).
- Run the validation function when the `submit` button is pressed.
- If the form submission fails display failure text next to the field that failed. 
  
the form in question:

![image](https://user-images.githubusercontent.com/12987958/34724429-c3eba11e-f51b-11e7-919f-3c765138ddbf.png)

**Comment by bkd705** [comment]
I'll take this one on! 😃

**Comment by teesloane** [comment]
Amazing! Let me know if you have any questions.
