### ISSUE TITLE
Create /submissions ui page

### ISSUE THREAD

**Issue by teesloane** [speakfriend/speakfriend#33]
The submissions page has the following attributes:

- it displays a list of all speaker submissions 
- optional: it has a search bar for filtering through submissions. 

Here are some possible steps to get started:

- [ ] clone how "/home" is implemented
- [ ] stub some dummy data that mirrors the form data (ie -  create a list of speaker proposals)
- [ ] iterate over the submissions and display them list (this does not need to be pretty - just plain text is fine for now)

**Comment by adamworrall** [comment]
I have some time over the next couple of days for this.

**Comment by teesloane** [comment]
Please do! Ping me if you have any questions.
