### ISSUE TITLE
Make login/register into a contained component

### ISSUE THREAD

**Issue by teesloane** [speakfriend/speakfriend#34]
Login / Register should be a component that allows switching between the two of them, bonus if you want to componentize inputs ala #26 

A picture is worth a 1000 lines of code (or something like that). This is just a rough mockup of functionality (not ui)

![switcher login](https://user-images.githubusercontent.com/12987958/35598278-6b6a9cc6-05f0-11e8-8de3-72ae25686179.png)

**Comment by teesloane** [comment]
Taking this in combination with #32

**Comment by dxnn** [comment]
Great. We'll have design feedback on this in the next couple of weeks, so don't worry about making it pretty for now. We'll also have a better idea of the specs for the fields during the registration process, so don't worry too much about those either.

**Comment by teesloane** [comment]
Sounds good; just gonna get enough of this for the basics to work :)
